version: "3.9"

volumes:
  kong-data:


networks:
  kong-network:
    driver: bridge
    ipam:
      config:
        # Configurable if an IP conflict occurs
        - subnet: 172.17.0.0/16

# can define static ip to kong-postgres, konga and kong (if needed)
services:
  kong-postgres:
    image: postgres:10
    user: root
    container_name: kong-postgres
    restart: always
    networks:
      - kong-network
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    ports:
      - "5432:5432"
    volumes:
      - kong-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong", "-d", "kong" ]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    user: root
    restart: on-failure
    networks:
      - kong-network
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    depends_on:
      - kong-postgres
    links:
      - kong-postgres:kong-postgres

  konga-prepare:
    image: pantsel/konga:latest
    user: root
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-postgres:5432/konga"
    restart: on-failure
    networks:
      - kong-network
    depends_on:
      - kong-postgres
    links:
      - kong-postgres

  kong:
    image: kong:latest
    container_name: kong
    user: root
    restart: always
    networks:
      - kong-network
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_SSL_CERT=/mnt/ssl/combine.pem
      - KONG_SSL_CERT_KEY=/mnt/ssl/server.key
      - KONG_ADMIN_API_SSL_LISTEN=0.0.0.8444

    depends_on:
      - kong-migrations
      - kong-postgres
    ports:
      - "8001:8001"
      - "8444:8444"
      - "80:8000"
      - "443:8443"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - /root/kong-certs:/mnt/ssl

  konga:
    image: pantsel/konga:latest
    container_name: konga
    user: root
    restart: always
    networks:
      - kong-network
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-postgres
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=konga
      - DB_PORT=5432
      - SSL_KEY_PATH=/app/konga-certs/server.key
      - SSL_CRT_PATH=/app/konga-certs/combine.crt
    depends_on:
      - kong-postgres
    ports:
      - "1337:1337"
    volumes:
      - /root/konga-certs:/app/konga-certs
